<template>
  <div>
    <!-- NavBar عام -->
    <NavBar
      v-if="
        ![
          'payment',
          'failed',
          'error',
          'resetpassword',
          'resetpassword2',
          'forgetpassword1',
          'forgetpassword2',
          'login',
          'signup',
          'trainerclient',
          'trainer',
          'trainerreviews',
          'trainersettings',
          'traineesettings',
          'trainee',
          'trainerplans',
          'trainercustomerservice',
          'traineecustomerservice',
          'trainerhome',
          'traineehome',
          'traineedashboard',
          'aboutustrainee',
          'sportstrainee',
          'contactustrainee',
          'search',
          'profile',
          'trainerviewprofile',
          'trainerinbox',
          'traineeinbox',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'mytrainers',
          'TrainerProfile',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
    <!-- SideBar عام -->
    <SideBar
      v-if="
        ![
          'landing',
          'payment',
          'failed',
          'error',
          'resetpassword',
          'resetpassword2',
          'forgetpassword1',
          'forgetpassword2',
          'login',
          'signup',
          'aboutus',
          'sports',
          'contactus',
          'traineesettings',
          'trainee',
          'traineehome',
          'traineecustomerservice',
          'traineedashboard',
          'aboutustrainee',
          'sportstrainee',
          'contactustrainee',
          'profile',
          'search',
          'trainerviewprofile',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'traineeinbox',
          'mytrainers',
          'mytrainers',
          'TrainerProfile',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
    <!-- SideBarTrainee -->
    <SideBarTrainee
      v-if="
        ![
          'landing',
          'payment',
          'failed',
          'error',
          'resetpassword',
          'resetpassword2',
          'forgetpassword1',
          'forgetpassword2',
          'login',
          'signup',
          'aboutus',
          'sports',
          'contactus',
          'trainerclient',
          'trainerreviews',
          'trainersettings',
          'trainer',
          'trainerplans',
          'trainerhome',
          'trainercustomerservice',
          'traineehome',
          'aboutustrainee',
          'sportstrainee',
          'contactustrainee',
          'profile',
          'search',
          'trainerviewprofile',
          'trainerinbox',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
    <!-- TraineeNavbar -->
    <TraineeNavbar
      v-if="
        ![
          'landing',
          'payment',
          'failed',
          'error',
          'resetpassword',
          'resetpassword2',
          'forgetpassword1',
          'forgetpassword2',
          'login',
          'signup',
          'aboutus',
          'sports',
          'contactus',
          'trainerclient',
          'trainerreviews',
          'trainersettings',
          'trainer',
          'trainerplans',
          'trainerhome',
          'trainercustomerservice',
          'traineecustomerservice',
          'traineedashboard',
          'traineesettings',
          'trainerviewprofile',
          'trainerinbox',
          'traineeinbox',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'mytrainers',
          'TrainerProfile',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
    <!-- TrainerNavbar -->
    <TrainerNavbar
      v-if="
        ![
          'landing',
          'payment',
          'failed',
          'error',
          'resetpassword',
          'resetpassword2',
          'forgetpassword1',
          'forgetpassword2',
          'login',
          'signup',
          'aboutus',
          'sports',
          'contactus',
          'trainerclient',
          'trainerreviews',
          'trainersettings',
          'trainer',
          'trainerplans',
          'trainerhome',
          'trainercustomerservice',
          'traineecustomerservice',
          'traineedashboard',
          'traineesettings',
          'trainerdashboard',
          'traineehome',
          'profile',
          'search',
          'aboutustrainee',
          'sportstrainee',
          'contactustrainee',
          'trainerinbox',
          'traineeinbox',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'mytrainers',
          'TrainerProfile',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
    <!-- SideBarAdmin -->
    <SideBarAdmin
      v-if="
        [
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'admintrainerprofile'
        ].includes($route.name)
      "
    />
    <!-- عرض الصفحات -->
    <router-view />
    <!-- Footer -->
    <FooterComp
      v-if="
        ![
          'payment',
          'failed',
          'error',
          'login',
          'signup',
          'trainerclient',
          'trainer',
          'trainerreviews',
          'trainersettings',
          'traineesettings',
          'trainer',
          'trainee',
          'trainerplans',
          'traineecustomerservice',
          'trainercustomerservice',
          'trainerhome',
          'traineedashboard',
          'trainerinbox',
          'traineeinbox',
          'adminoverview',
          'managetrainers',
          'managetrainees',
          'adminbookings',
          'adminpayments',
          'adminreviews',
          'mytrainers',
          'TrainerProfile',
          'admintrainerprofile',
        ].includes($route.name)
      "
    />
  </div>
</template>
<script>
import FooterComp from "./components/FooterComp.vue";
import NavBar from "./components/NavBar.vue";
import SideBar from "./components/SideBar.vue";
import SideBarTrainee from "./components/SideBarTrainee.vue";
import TraineeNavbar from "./components/TraineeNavbar.vue";
import TrainerNavbar from "./components/TrainerNavbar.vue";
import SideBarAdmin from "./components/SideBarAdmin.vue";
export default {
  name: "App",
  components: {
    NavBar,
    FooterComp,
    SideBar,
    SideBarTrainee,
    TraineeNavbar,
    TrainerNavbar,
    SideBarAdmin,
  },
};
</script>
<style></style>
